"""Grade-gated question bank for beyond-the-classroom.

every question: 3 modalities (visual / audio-via-tts / kinesthetic) + adaptive
rewrites + option notes. bank key = (band, subject). quiz picks from the band
the learner's profile grade maps to.

bands: foundation (grades 1-3) | intermediate (4-7) | senior (8-9) | fet (10-12)
"""

def _q(band, subject, topic, q, context, options, answer, notes, rewrites, visual, kinesthetic):
    return {
        "band": band, "subject": subject, "topic": topic,
        "q": q, "context": context, "options": options, "answer": answer,
        "option_notes": notes, "rewrites": rewrites,
        "visual": visual, "kinesthetic": kinesthetic,
    }

BANK = {
    # ---------------- foundation (grades 1-3) ----------------
    "foundation": [
        _q("foundation", "Mathematics", "Number bonds",
           "What goes in the empty box?  7 + [ ] = 10",
           "Number bonds to 10",
           ["2", "3", "4", "5"], 1,
           {"0": "2 is too small. 7 + 2 = 9, and 9 is not 10 yet.",
            "2": "7 + 4 = 11. That went one step too far.",
            "3": "7 + 5 = 12. That is more than 10."},
           ["Use your fingers: hold up 7 fingers. Keep putting fingers up until you reach 10. How many extra fingers did you need? 3!",
            "Picture a bus with 7 seats filled. The bus has 10 seats. The empty seats are the answer. Count the empty seats: 3.",
            "Start at 7 and count up to 10 on the number line: 8, 9, 10. You took 3 steps. That is the answer.",
            "Step 1: what do we add to 7 to get 10? Step 2: count 8 (1), 9 (2), 10 (3). Three steps: the box needs 3."],
           "Picture 10 spots on a ten-frame, like an egg box with 10 holes. 7 eggs are in. The empty holes are the answer. Count them: 3 empty holes. 7 + 3 = 10.",
           "Grab 10 small things - buttons, beans, anything. Put 7 in one hand. Now move them one at a time until all 10 are in that hand. The ones you moved are the answer: you moved 3.",
        ),
        _q("foundation", "English", "Sounds and letters",
           "Which word starts with the same sound as 'sun'?",
           "Beginning sounds",
           ["moon", "sock", "fan", "cup"], 1,
           {"0": "Moon starts with 'mmm', a different sound from 'sss'.",
            "2": "Fan starts with 'fff'. Not the same as 'sss'.",
            "3": "Cup starts with 'cuh'. The sun sound is 'sss'."},
           ["Say 'sun' slowly: sss-unn. Now say each choice slowly. 'Sock' starts with the same sss sound.",
            "Put your hand near your mouth and say 'sss' — it tickles like a snake! Snake, sun, sock all start with that tickle.",
            "Picture a snake saying 'sss'. Sun and sock both start with the snake sound. Moon starts with lips pressed together: mmm.",
            "Step 1: find the first sound of 'sun' = sss. Step 2: check each word's first sound. Step 3: sock = sss. Match!"],
           "Picture the sun in the sky going 'sss'. Next to it, a sock. They both start with the same snake-letters. The moon is quiet and round, making a different 'mmm' shape with your lips.",
           "Say 'sun' out loud and watch your mouth: your teeth come together and air hisses out — sss. Now say 'sock': same hiss! Now 'moon': your lips press together. Your mouth just showed you the answer.",
        ),
        _q("foundation", "Life skills", "Healthy habits",
           "What does your body need most of every day?",
           "Caring for your body",
           ["sweets", "water", "cool air", "screen time"], 1,
           {"0": "Sweets are a sometimes-food. Your body cannot run on them.",
            "2": "Cool air feels nice but your body does not store it — it needs water all day.",
            "3": "Screens are fun but your eyes and body get tired. They are not a need."},
           ["Your body is like a plant: plants need water every day, and so do you. Water is what your body needs most.",
            "Picture a car: water keeps your body's engine cool and running. No water, no go!",
            "You can skip sweets, screens and cool air for a whole day and be fine. Skip water and your body sends a thirsty alarm. Needs are the things your body cannot skip.",
            "Step 1: a need is something your body cannot work without. Step 2: test each one. Step 3: water is the one your body runs on."],
           "Picture a big glass of water next to a small sweet, a TV and an open window. Your body is a jug that slowly empties all day. Only one thing refills the jug: water. Glug, glug, glug.",
           "Breathe in and feel how dry your mouth is right now. Take a sip of water if there is some near you — feel how your mouth says thank you. That happy-mouth feeling is your body telling you water is the thing it needs most.",
        ),
    ],
    # ---------------- intermediate (grades 4-7) ----------------
    "intermediate": [
        _q("intermediate", "Mathematics", "Fractions",
           "Sipho eats 1/4 of a pizza and Thandi eats 2/8 of the same pizza. Who ate more?",
           "Equivalent fractions",
           ["Sipho", "Thandi", "the same amount", "cannot tell"], 2,
           {"0": "Sipho ate 1/4. Turn 2/8 into quarters: 2/8 = 1/4. They are equal, so Sipho did not eat more.",
            "1": "2/8 looks bigger because 2 is bigger than 1, but the pieces are smaller. 2/8 simplifies to 1/4 — the same as Sipho.",
            "3": "You can tell! Both fractions name the same amount once you simplify them."},
           ["Cut a pizza into 8 and take 2 slices. Now cut a pizza into 4 and take 1. Line them up — they are exactly the same size.",
            "Simplify first: 2/8. Divide top and bottom by 2: 1/4. Now compare 1/4 with 1/4. Same!",
            "Picture the pizza: 8 small slices with 2 taken = a quarter of the pizza gone. 4 big slices with 1 taken = the same quarter gone.",
            "Step 1: simplify 2/8 = 1/4. Step 2: compare 1/4 and 1/4. Step 3: equal, so both ate the same amount."],
           "Draw one pizza bar: shade 1 of 4 blocks. Below it draw the same bar split into 8: shade 2 blocks. Slide the shaded parts together — they cover exactly the same ground. The shaded area IS the answer: equal.",
           "Fold a paper strip in half, then in half again: 4 sections, colour 1. Now take another strip, fold it in half 3 times: 8 sections, colour 2. Tear off the coloured bits and hold them side by side. Same size. Your hands proved 1/4 = 2/8.",
        ),
        _q("intermediate", "Natural science", "States of matter",
           "Water vapour turns back into liquid on a cold mirror. What is this called?",
           "Changes of state",
           ["evaporation", "condensation", "melting", "freezing"], 1,
           {"0": "Evaporation is liquid turning into gas — the opposite of what happened on the mirror.",
            "2": "Melting is a solid turning into liquid, like ice to water. No solid was involved here.",
            "3": "Freezing is liquid turning into solid, like water to ice. The mirror water stayed liquid."},
           ["Gas to liquid = condensation. It is why a cold glass of juice 'sweats' on a hot day: the water in the air touches the cold surface and turns back to liquid.",
            "Con = together, dens = make dense. The vapour particles slow down on the cold mirror and crowd back together into droplets.",
            "Bathroom mirror after a hot shower: the warm vapour hits the cool glass and turns to droplets. That fog IS condensation happening.",
            "Step 1: what state did it start in? gas. Step 2: what state did it end in? liquid. Step 3: gas to liquid = condensation."],
           "Picture tiny dotted arrows (vapour) flying toward a cold blue mirror. At the glass they slow down and stack into small round droplets you can see. The arrows becoming droplets at the cold surface is the whole picture: gas in, liquid out — condensation.",
           "Breathe onto any window or mirror right now. Feel the warm damp breath hit the cool glass, then look: fog droplets. You just made condensation with your own breath. Wipe it and breathe again — same science, every time.",
        ),
        _q("intermediate", "English", "Comprehension: inference",
           "'Nomvula clutched her bag tighter as the taxi rattled past the market.' What can you infer about how Nomvula felt?",
           "Reading between the lines",
           ["she was relaxed", "she was nervous or protective", "she was sleepy", "she was hungry"], 1,
           {"0": "Relaxed people do not clutch their bags tighter. Her body is showing tension.",
            "2": "Nothing in the sentence points to sleepiness. Clutching is an awake, tense action.",
            "3": "Hunger is not connected to holding a bag. The clue is in the clutching."},
           ["People clutch their bags tighter when they feel unsafe or want to protect what is inside. Her hands are telling you her feeling.",
            "'Clutched' + 'tighter' = holding on hard. We hold on hard when we are nervous or guarding something.",
            "Picture yourself on a bumpy taxi with your bag. If someone grabbed it, you would pull it close. The writer chose 'clutched' to show worry, not comfort.",
            "Step 1: find the action word — clutched. Step 2: ask when people do that — when nervous or protective. Step 3: the inference is nervous/protective."],
           "Picture Nomvula's hands: knuckles white, pressing the bag into her body as the taxi shakes. Now picture relaxed hands resting open on a lap. The two pictures are opposites — and the sentence paints the first one. White-knuckle hands = nervous.",
           "Hold your bag or a book against your chest right now and squeeze it tight. Feel your shoulders and arms? That tightness is what 'clutched tighter' does to a body. Bodies tense like that when they feel unsure — not when relaxed or sleepy.",
        ),
    ],
    # ---------------- senior (grades 8-9) ----------------
    "senior": [
        _q("senior", "Mathematics", "Linear equations",
           "Solve for x:  3(x - 2) + 4 = 2x + 9",
           "Equations with brackets",
           ["x = 5", "x = 7", "x = 11", "x = 13"], 2,
           {"0": "Check: 3(5-2)+4 = 13, but 2(5)+9 = 19. Not equal, so 5 is wrong. Expand first: 3x - 6 + 4 = 3x - 2. Then 3x - 2 = 2x + 9 gives x = 11.",
            "1": "Check: 3(7-2)+4 = 19 and 2(7)+9 = 23. Not equal. The correct path: 3x - 2 = 2x + 9, so x = 11.",
            "3": "Check: 3(13-2)+4 = 37 and 2(13)+9 = 35. Close but not equal — you probably made a sign slip. It is x = 11."},
           ["Expand the bracket first: 3x - 6 + 4 = 2x + 9, so 3x - 2 = 2x + 9. Move the x's left: x = 11.",
            "Balance idea: the two sides are scales. Simplify each side fully before moving anything. Left side secretly equals 3x - 2 — that is the shortcut.",
            "Substitute x = 11 to test: left = 3(9) + 4 = 31, right = 22 + 9 = 31. Equal — it works. Testing your answer catches slips.",
            "Step 1: expand: 3x - 6 + 4 = 2x + 9. Step 2: simplify: 3x - 2 = 2x + 9. Step 3: subtract 2x: x - 2 = 9. Step 4: add 2: x = 11."],
           "Picture a balance scale. Left pan: three x-boxes, a -6 weight and a +4 weight cancel to -2. Right pan: two x-boxes and a 9. Remove two x-boxes from both pans — they stay balanced. One x-box and -2 on the left, 9 on the right. Slide the -2 across: x = 11.",
           "Grab 11 coins as your answer-checker. Work the left side on paper with x = 11: 3 lots of (11 - 2) plus 4. Count it out: 3 x 9 = 27, plus 4 = 31. Now the right side: 2 x 11 = 22, plus 9 = 31. Both hands land on 31 — the scales balance at x = 11.",
        ),
        _q("senior", "Natural sciences", "Photosynthesis",
           "Which word equation correctly represents photosynthesis?",
           "Life processes",
           ["glucose + oxygen -> carbon dioxide + water",
            "carbon dioxide + water -> glucose + oxygen",
            "water + oxygen -> glucose + carbon dioxide",
            "glucose -> carbon dioxide + oxygen"], 1,
           {"0": "That is respiration — it runs the opposite direction, releasing energy from glucose.",
            "2": "Oxygen is a product of photosynthesis, not an ingredient. Water and CO2 go in.",
            "3": "That skips the inputs entirely. Photosynthesis needs carbon dioxide AND water to build glucose."},
           ["Photosynthesis builds food. Building means inputs become a bigger molecule (glucose) and oxygen is released: CO2 + water in, glucose + oxygen out.",
            "Think 'photo' = light-powered cooking. Ingredients: carbon dioxide and water. Meal: glucose. Waste gas: oxygen.",
            "Plants are the reverse of us: we breathe O2 in and CO2 out; plants take our CO2 plus water and light to make glucose, releasing O2.",
            "Step 1: inputs are CO2 + H2O (with light + chlorophyll). Step 2: outputs are glucose + O2. Step 3: only one option has both right."],
           "Picture a leaf as a kitchen. In one door: CO2 (tiny grey dots) and water (blue drops) pushed in by sunlight arrows. Out the other door: a sugar cube (glucose) and O2 bubbles floating away. Two in, two out — that order is the answer.",
           "Put a glowing water-plant (elodea) in water in the sun — or picture it: you would SEE bubbles streaming off the leaves. Those bubbles are oxygen leaving. Sunlight goes in, bubbles come out, glucose is built inside. Seeing the bubbles = seeing photosynthesis's output.",
        ),
        _q("senior", "Economic and management sciences", "Profit and loss",
           "A tray of muffins costs R120 to make and sells for R15 each. The tray holds 10 muffins. What is the profit?",
           "Basic business maths",
           ["R30", "R150", "R270", "R15"], 0,
           {"1": "R150 is revenue (10 x R15), not profit. You still paid R120 for ingredients.",
            "2": "R270 adds revenue and cost together — they must be subtracted.",
            "3": "R15 is the price of one muffin, not the profit on the whole tray."},
           ["Revenue = 10 x R15 = R150. Profit = revenue - cost = R150 - R120 = R30.",
            "Every sale first pays back cost: 8 muffins cover the R120 (8 x 15 = 120). Muffins 9 and 10 are pure profit: 2 x 15 = R30.",
            "Picture a jar: R150 of notes goes in, R120 goes out to pay for ingredients. What stays in the jar is profit: R30.",
            "Step 1: revenue = 10 x 15 = 150. Step 2: profit = 150 - 120. Step 3: R30."],
           "Picture two jars. Jar IN fills with 10 x R15 = R150 of notes. Jar OUT (ingredients) holds R120. Pour OUT back from IN — 3 tens and nothing left over: R30 stays in the IN jar. The remaining notes ARE the profit.",
           "Use 10 buttons as muffins. Each button is worth R15: lay them in a row = R150 of sales. Now pay the bakery: remove 8 buttons' worth (R120). You are holding 2 buttons = R30. That is the profit you can feel.",
        ),
    ],
    # ---------------- fet (grades 10-12) ----------------
    "fet": [
    _q("fet", "Mathematics", "Functions",
       "For f(x) = 2x² - 8x + 3, the coordinates of the turning point are:",
       "Parabolas",
       ["(2, -5)", "(2, 5)", "(-2, 27)", "(4, 3)"], 0,
       {"1": "x = 2 is right, but f(2) = 2(4) - 16 + 3 = -5, not +5. Watch the sign when substituting.",
        "2": "x = -b/2a = 8/4 = 2, not -2. And f(-2) = 27 is the y-value for the wrong x.",
        "3": "4 is a root-ish guess, not the axis of symmetry. Use x = -b/2a = 8/4 = 2, then f(2) = -5."},
       ["Axis of symmetry: x = -b/2a = 8/(2·2) = 2. Substitute back: f(2) = 8 - 16 + 3 = -5. Turning point (2, -5).",
        "The parabola opens up (a > 0), so the turning point is a minimum. Find where the mirror line sits (x = 2), then how low the curve dips (f(2) = -5).",
        "Complete the square: 2(x² - 4x) + 3 = 2(x - 2)² - 8 + 3 = 2(x - 2)² - 5. Written as a(x-p)² + q, the turning point jumps out: (2, -5).",
        "Step 1: x = -b/2a = 2. Step 2: f(2) = 2(4) - 16 + 3 = -5. Step 3: point (2, -5)."],
       "Picture the U-shaped parabola with arms up. The mirror line cuts it at x = 2. Slide your finger down the U to its lowest point: two across, five down — the bowl's bottom sits at (2, -5). That dip is the turning point.",
       "Plot it with your hands: at x = 0 the curve is at 3 (thumbs up). At x = 2: count 2(2)²=8, minus 16, plus 3 = -5 (hands drop). At x = 4: back up to 3. The dip between your two high hands bottoms out at (2, -5). You traced the whole parabola.",
    ),
    _q("fet", "Physical sciences", "Momentum",
       "A 2 kg ball moves at 3 m/s east. It hits a stationary 1 kg ball. After the collision the 2 kg ball moves at 1 m/s east. The 1 kg ball's velocity is:",
       "Conservation of momentum",
       ["4 m/s east", "2 m/s west", "4 m/s west", "3 m/s east"], 0,
       {"1": "Total momentum before = 6 kg·m/s. After: 2(1) + 1(v) = 6, so v = 4 east. West would make the totals negative and break conservation.",
        "2": "The stationary ball is hit from behind — it cannot fly backwards past the incoming ball in this setup.",
        "3": "3 m/s would give after-total 2(1) + 1(3) = 5, losing 1 kg·m/s. Momentum must be conserved exactly."},
       ["Before: p = 2(3) + 1(0) = 6. After: 2(1) + 1(v) = 6. So v = 4 m/s east.",
        "Momentum is never lost in a collision — the 2 kg ball slowed down by 2 units of 'push', and all of that push passed into the small ball, taking it from 0 to 4.",
        "Think of Newton's cradle or pool balls: the cue ball slows, the object ball speeds up, the total stays the same. Slow down 2 x 2 = 4 units there, gain 1 x 4 there.",
        "Step 1: p(before) = (2)(3) + (1)(0) = 6. Step 2: p(after) = (2)(1) + (1)v. Step 3: 2 + v = 6. Step 4: v = 4 m/s east."],
       "Picture two carts on a track with momentum arrows drawn above: one thick arrow '6' over the big cart before the crash. After: the big cart's arrow is '2', and above the small cart a fresh arrow '4' — the two after-arrows stacked equal the original 6. Arrow lengths must always balance.",
       "Push two toy cars or two books on a smooth table: flick the heavy one into the resting light one. Watch the light one zip off faster than the heavy one was moving — the push transfers. The heavy one slows, the light one races: the trade is momentum conservation you can see and hear.",
    ),
    _q("fet", "Accounting", "Financial statements",
       "Which of the following is an asset?",
       "The accounting equation",
       ["Bank overdraft", "Vehicles", "Salaries paid", "Sales"], 1,
       {"0": "An overdraft is money you owe the bank — a liability, the opposite of an asset.",
        "2": "Salaries paid is an expense — it is consumed, not owned.",
        "3": "Sales is income. Income is earned, not owned; it becomes an asset only once it sits in the bank."},
       ["An asset is something the business OWNS that has value. Vehicles are owned and have value. The others are owed (overdraft), consumed (salaries) or earned (sales).",
        "Test each with: 'does the business own it, and does it bring future benefit?' Vehicles pass. An overdraft is owed back, salaries were used up, sales were earned — not owned things.",
        "Assets = what you have. Liabilities = what you owe. Expenses/income = what flowed through. Vehicles sit in the 'have' box.",
        "Step 1: recall the definition of an asset. Step 2: apply it to each option. Step 3: only vehicles pass the owned-with-value test."],
           "Picture three boxes in the storeroom of the business: a green OWN box, a red OWE box, a grey FLOWED-THROUGH box. The delivery van parks itself firmly in the green OWN box. The overdraft letter goes red, the salary slip grey, the sales receipt grey. The van is the asset.",
           "Walk through your own house pointing at things: this is mine and worth something (asset), this I still owe money on (liability). Do the same for a taxi business: the minibus taxi = owned, valuable, working for the business every day. That is what an asset is — you just pointed at one.",
    ),
    ],
}

# index helpers
def bank_for_band(band):
    return [q for q in BANK[band]] if band in BANK else BANK["intermediate"]

def subjects_in_band(band):
    return sorted({q["subject"] for q in bank_for_band(band)})
